### ISSUE TITLE
[FEATURE] create issue and pull request template

### ISSUE THREAD

**Issue by Kira272921** [avneesh0612/react-nextjs-snippets#3]
### Description

Create issues and pull request templates.

Here are the docs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by lavakush07** [comment]
I would love to work on this issue.Pls,assign me

**Comment by avneesh0612** [comment]
Cool!

**Comment by avneesh0612** [comment]
are you working on this @lavakush07?

**Comment by lavakush07** [comment]
Yess, I am working on it and I will give u an update tom ?


> are you working on this @lavakush07?

Yess,I am on it and I will  finish it by tom

**Comment by avneesh0612** [comment]
Okay, cool!

**Comment by avneesh0612** [comment]
Hey! Any updates?

**Comment by avneesh0612** [comment]
Hwy, since there are no updates for a long time. I am unassigning this, if you want to continue then just lmk
