### ISSUE TITLE
[FEATURE] Add imports to TypeScript in React 

### ISSUE THREAD

**Issue by Kira272921** [avneesh0612/react-nextjs-snippets#41]
### Description

Add the [imports code snippets](https://github.com/avneesh0612/react-nextjs-snippets/blob/main/packages/vscode/snippets/react-javascript.json#L1-L21) in the [React TypeScript](https://github.com/avneesh0612/react-nextjs-snippets/blob/main/packages/vscode/snippets/react-javascript.json) file

**Comment by itisaby** [comment]
HI! I would like to take this issue :)

**Comment by avneesh0612** [comment]
Sure!

**Comment by itisaby** [comment]
Hi @avneesh0612 so all I need to do is to add the import snippets into the react typescript file but can you please tell me which ones to add?

**Comment by Kira272921** [comment]
Hey @itisaby, you have to add these [import snippets](https://github.com/avneesh0612/react-nextjs-snippets/blob/main/packages/vscode/snippets/react-javascript.json#L2-L20) to the [`react-typescript.json`](https://github.com/avneesh0612/react-nextjs-snippets/blob/main/packages/vscode/snippets/react-typescript.json) file. Just convert them in to typescript syntax and add them to the [`react-typescript.json`](https://github.com/avneesh0612/react-nextjs-snippets/blob/main/packages/vscode/snippets/react-typescript.json) file. You can use this web application by which you can greate the snippets by more easily :D https://snippet-generator.app/

**Comment by itisaby** [comment]
Thank You @Kira272921 , I'm on it :)
