### ISSUE TITLE
[FEATURE] Add Code of Conduct

### ISSUE THREAD

**Issue by avneesh0612** [avneesh0612/react-nextjs-snippets#6]
### Description

Add a code of conduct file. More details- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by AKhatabdev** [comment]
Hello,

I would like to work on this.

Kind regards

**Comment by avneesh0612** [comment]
Cool!

**Comment by AKhatabdev** [comment]
Hello,

I won't be able to work on this.

Kind regards

**Comment by APOORVANAGAR-2002** [comment]
Hi,
I am interested to work on the issue.

**Comment by avneesh0612** [comment]
Okay cool
